### ISSUE TITLE
parameter problem

### ISSUE THREAD

**Issue by Xinya-liuliu** [TravisL24/HECKTOR#2]
Hi,  I have a question about filepath "https://github.com/TravisL24/HECKTOR/blob/main/hecktor/src/data/utils.py"  line 176,

        def Execute(self, image1):
            r"""
        Execute(ResampleImageFilter self, Image image1) -> Image
        Execute the filter on the input image
        """
        return _SimpleITK.ResampleImageFilter_Execute(self, image1)

but  you write like this:

    resampled_sitk_image = resample_filter.Execute(sitk_image,
                                                   new_size,
                                                   sitk.Transform(),
                                                   sitk_interpolator,
                                                   orig_origin,
                                                   new_spacing,
                                                   orig_direction,
                                                   fill_value,
                                                   orig_pixelid)

Why  Execute() takes 2 positional arguments but 10 were given?
I just tried it and it will give an error, I am curious what is the reason for you to write this?

**Comment by TravisL24** [comment]
![image](https://user-images.githubusercontent.com/26930037/179389839-8ae90377-9486-4a1c-bcf8-2aaa376985a5.png)

您好，这里调用了SimpleITK的Execute方法。我的simpleitk版本为1.2.4。也许可以尝试检查一下您的库版本，如果有需要我再把我的环境文件发给给您。其他相关问题也可以交流。
